### ISSUE TITLE
Update docs to include js-ng [development_ng]

### ISSUE THREAD

**Issue by ranatrk** [threefoldfoundation/info_gridmanual#138]
## Phase 1
- [x] Getting Started
  - [x] 3sdk install
  - [x] 3sdk use
  - [x] Deploy your first solution
     - [x] Start the 3SDK
- [x] Admin panel overview (new admin dashboard)
- [x] Develop
  - [x] Provisioning code
  - [x] Admin panel (Dashboard)
  - [x] Jumpscale (js-ng internals)
  - [x] Chatflow (how to create chatflows)
  - [x] Flist
- [x] Simulator
- [x] Farm management & setup
  - [x] Farm management
  - [x] Wallet management

## Phase 2 (After capacity reservation)
https://github.com/threefoldfoundation/info_gridmanual/issues/197
